services:

  app:
    build:
      context: .
    container_name: app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      GITHUB_APP_NAME: shobapp24
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/ShobApp24
      BETTER_AUTH_URL: http://localhost:3000
      MAX_LIMIT: 100
      REDIS_URL: redis://redis:6379
      RABBITMQ_URL: amqp://rabbitmq:5672
      PORT: 3000
      CORS_ORIGIN_URL: https://githubs24.vercel.app
      COOKIE_PREFIX: shobapp24
    command: pnpm run start
    depends_on:
      postgres:
        condition: service_healthy
      prisma:
        condition: service_completed_successfully
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    restart: unless-stopped

  prisma:
    build:
      context: .
    container_name: prisma_migrate
    environment:
      DATABASE_URL: postgresql://postgres:secret@postgres:5432/ShobApp24
    command: npx prisma db push
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: ShobApp24
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - rabbitmq_data:/data
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
