import { EventType } from "@prisma/client";

export const githubWorkflowActionRules: Record<EventType, readonly string[]> = {
  installation: ["created", "deleted", "new_permissions_accepted", "suspend", "unsuspend"],
  star: ["created", "deleted"],
  watch: ["started"],
  label: ["created", "deleted", "edited"],
  issues: [
    "assigned",
    "closed",
    "deleted",
    "demilestoned",
    "edited",
    "labeled",
    "locked",
    "milestoned",
    "opened",
    "pinned",
    "reopened",
    "transferred",
    "typed",
    "unassigned",
    "unlabeled",
    "unlocked",
    "unpinned",
    "untyped",
  ],
  issue_comment: ["created", "deleted", "edited"],
  push: [],
  pull_request: [
    "assigned",
    "auto_merge_disabled",
    "auto_merge_enabled",
    "closed",
    "converted_to_draft",
    "demilestoned",
    "dequeued",
    "edited",
    "enqueued",
    "labeled",
    "locked",
    "milestoned",
    "opened",
    "ready_for_review",
    "reopened",
    "review_request_removed",
    "review_requested",
    "synchronize",
    "unassigned",
    "unlabeled",
    "unlocked",
  ],
  repository: [
    "archived",
    "created",
    "deleted",
    "edited",
    "privatized",
    "publicized",
    "renamed",
    "transferred",
    "unarchived",
  ],
  commit_comment: ["created"],
  fork: [],
  pull_request_review: ["dismissed", "edited", "submitted"],
  create: [],
  delete: [],
  workflow_job: ["completed", "in_progress", "queued", "waiting"],
  workflow_run: ["completed", "in_progress", "requested"],
};

export function getGitHubWorkflowActions(eventType: EventType): readonly string[] {
  return githubWorkflowActionRules[eventType];
}
