name: Production Deploy

on:
  workflow_run:
    workflows:
      - CI Pipeline
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tag
        id: meta
        run: |
          echo "TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build \
            -t thearkan/shobapp24:${{ steps.meta.outputs.TAG }} \
            -t thearkan/shobapp24:latest \
            .

      - name: Push Docker images
        run: |
          docker push thearkan/shobapp24:${{ steps.meta.outputs.TAG }}
          docker push thearkan/shobapp24:latest

      - name: Deploy to GCP VM
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            cd /projects

            # Backup current deployed version
            if [ -f current.env ]; then
              cp current.env previous.env
            fi

            # Set new image tag
            echo "IMAGE_TAG=${{ steps.meta.outputs.TAG }}" > current.env

            # Export image tag
            export $(cat current.env | xargs)

            echo "Pulling new image..."
            docker compose pull

            echo "Starting containers..."
            docker compose up -d --remove-orphans

            echo "Waiting for healthcheck..."
            sleep 20

            CONTAINER_ID=$(docker compose ps -q backend)

            HEALTH_STATUS=$(docker inspect \
              --format='{{json .State.Health.Status}}' \
              $CONTAINER_ID | tr -d '"')

            if [ "$HEALTH_STATUS" != "healthy" ]; then
              echo "Deployment failed. Rolling back..."

              if [ -f previous.env ]; then
                cp previous.env current.env

                export $(cat current.env | xargs)

                docker compose pull
                docker compose up -d --remove-orphans

                echo "Rollback completed"
                exit 1
              else
                echo "No previous deployment found"
                exit 1
              fi
            fi

            echo "Deployment successful"

            docker image prune -af

